version: "3.9"

services:
  app:
    image: victor/java25:latest
    #image: mt5-db-sync:latest
    container_name: agent
    working_dir: /workspace

    # 你的 JAR + logback.xml 都在当前目录
    volumes:
      - /mnt/libs:/mnt/libs
      - /mnt/temp:/mnt/temp
      - $PWD:/workspace
      - $PWD/ai.sh:/usr/bin/ai.sh
       - $HOME/.tmux.conf:/root/.tmux.conf
      - $HOME/.m2:/root/.m2
      - $HOME/.codex:/root/.codex
      - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.aws:/root/.aws:ro
      - $HOME/bin:/root/bin:ro
    # 指定 JVM 参数 → 从外部 logback.xml 读取
    # bash -c "/app/run.sh"
    # ai.sh "$PROFILE" "$SRC_DIR/task.txt"
    # codex --profile "$PROFILE" "$@"
    command: >
      bash
    env_file:
      - .env.container
    environment:
      APP_ENV: local

